<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LINQPad.Runtime" Version="8.3.7" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.9.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
		<PackageReference Include="NTextEditor.Languages.CSharp" Version="1.0.1" />
		<PackageReference Include="NTextEditor.View.WinForms" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolutionMap\SolutionMap.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

</Project>